PROC DIVIDE
    
    MOV COUNTER,'/'
    CMP OPERAND,0
    JE  ALTERDIVIDE
    MOV AX,OPERAND
    DIV BX
    MOV OPERAND,AX
    MOV REMAINDER,DX
    MOV DIVISOR,BX
    JMP AFTERMATH
    
    ALTERDIVIDE:
    MOV OPERAND,BX
    XOR BX,BX
    JMP L1
    
    D_REMAINDER: ;CALCULATE FLOTING POINTS
    CMP POINT,0
    JE P
    JMP P_NEXT
    P:
    MOV AH,2
    MOV DL, '.'
    MOV POINT,1
    INT 21H
    
    P_NEXT:
    XOR AX,AX
    MOV AX,10
    
    MUL REMAINDER
    DIV DIVISOR
    MOV OPERAND,AX
    MOV REMAINDER,DX
    
    CMP VAR1,DX  ;;;TO STOP INFITE LOOP
    JE START
    CMP VAR2,DX
    JE R2
    MOV VAR2,DX
    R2:
    MOV VAR1,DX
    
    
    JMP AFTERMATH 
    
    RET
    DIVIDE ENDP